apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: parsec-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_freqmine
        name: parsec-freqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset --cpu-list 0-5 ./run -a run -S parsec -p freqmine -i native -n 8"]
        # realistically, requires <= 1GB of RAM
        resources:
          requests:
            memory: "8G"
            cpu: "3900m"
          limits:
            memory: "8G"
            cpu: "6000m"
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: e2-standard-8
