apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-dedup
  labels:
    name: parsec-dedup
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_dedup
        name: parsec-dedup
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset --cpu-list 0-7 ./run -a run -S parsec -p dedup -i native -n 8"]
        # realistically, requires <= 2GB of RAM
        resources:
          requests:
            memory: "20G"
            cpu: "3900m"
          limits:
            memory: "31G"
            cpu: "8000m"
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: e2-standard-8
