apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: parsec-ferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset --cpu-list 0-3 ./run -a run -S parsec -p ferret -i native -n 6"]
        # realistically, requires <= 2GB of RAM
        resources:
          requests:
            memory: "31G"
            cpu: "3500m"
          limits:
            memory: "31G"
            cpu: "4000m"
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: n2d-highmem-4
