#!/bin/sh -ex

source $(dirname "$0")/env

server=$(kubectl get nodes -o=jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" | grep memcache-server)

gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$server --zone europe-west3-a --command "$(cat $(dirname "$0")/setup-memcached)"

gcloud compute scp --ssh-key-file cloud-computing --zone europe-west3-a $(dirname "$0")/measure-cpu-py ubuntu@$server:/tmp/measure-cpu-py
gcloud compute scp --ssh-key-file cloud-computing --zone europe-west3-a $(dirname "$0")/memcached-default-config ubuntu@$server:/tmp/memcached.conf
gcloud compute scp --ssh-key-file cloud-computing --zone europe-west3-a $(dirname "$0")/conf-memcached-cmd ubuntu@$server:/tmp/conf-memcached

gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$server --zone europe-west3-a --command "sudo cp /tmp/memcached.conf /etc/memcached.conf && chmod +x /tmp/conf-memcached && sudo systemctl restart memcached"

agent=$(kubectl get nodes -o=jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" | grep client-agent)
measure=$(kubectl get nodes -o=jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" | grep client-measure)

gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$agent --zone europe-west3-a --command "$(cat $(dirname "$0")/setup-mcperf)"
gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$measure --zone europe-west3-a --command "$(cat $(dirname "$0")/setup-mcperf)"
