#!/bin/sh -ex

source $(dirname "$0")/env

server=$(kubectl get nodes -o=jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" | grep memcache-server)

gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$server --zone europe-west3-a --command "$(cat $(dirname "$0")/setup-scheduler)"

gcloud compute scp --ssh-key-file cloud-computing --zone europe-west3-a scheduler.py ubuntu@$server:/tmp
gcloud compute scp --ssh-key-file cloud-computing --zone europe-west3-a scheduler_logger.py ubuntu@$server:/tmp

gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$server --zone europe-west3-a --command "sudo bash /tmp/conf-memcached 2 2"

echo "Now run:"
echo "gcloud compute ssh --ssh-key-file cloud-computing ubuntu@$server --zone europe-west3-a"
