#!/bin/sh

sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
DEBIAN_FRONTEND=noninteractive sudo apt-get update
DEBIAN_FRONTEND=noninteractive sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo systemctl restat docker

sudo docker pull anakli/cca:parsec_blackscholes
sudo docker pull anakli/cca:parsec_canneal
sudo docker pull anakli/cca:parsec_dedup
sudo docker pull anakli/cca:parsec_ferret
sudo docker pull anakli/cca:parsec_freqmine
sudo docker pull anakli/cca:splash2x_radix
sudo docker pull anakli/cca:parsec_vips

sudo apt install -y python3-docker
