#!/bin/sh -ex

source $(dirname "$0")/env

# gsutil mb $KOPS_STATE_STORE

kops create -f part2a.yaml || true

kops create secret --name part2a.k8s.local sshpublickey admin -i $PWD/cloud-computing.pub || true

kops update cluster --name part2a.k8s.local --yes --admin || true

kops validate cluster --wait 10m

kubectl get nodes -o wide
